name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  code-check:
    name: code-check
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/servicewall/*,github.com/Servicewall/*
    steps:
      - uses: actions/checkout@v2

      - name: Configure git for private modules
        env:
          GH_CI_TOKEN: ${{ secrets.GH_CI_TOKEN }}
        run: git config --global url."https://Servicewall-CI:${GH_CI_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          args: --timeout 3m

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: make lint

      - name: Test
        run: make test
